name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    #- name: Display the path
    #  run:  |
    #    set path_var = echo %PATH%
    #    echo %path_var%
    #    echo %dir%
    #  shell: cmd
    #- name: Run script from scripts folder
    #  run: ./scripts/setVar.cmd "Jamal"  
    #  shell: cmd
    - name: Run shell script
      run: |
           OUTPUT_SHELL=$(uname -a)
           echo '::set-output name=OUTPUT_SHELL::$OUTPUT_SHELL'
      shell: sh
      id: shell-output
    - name: Display Output
      run: |
           echo ${{ steps.shell-output.outputs.OUTPUT_SHELL }} 
