name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run shell script
      run: |
           chmod 777 scripts/setEnv.sh
           echo "::set-output name=save-var::$(scripts/setEnv.sh)\n"
           if: ${{ save-var == 'yes' }}
      shell: sh
      id: shell-output
  #  - name: Display Output
 #   if: ${{ steps.shell-output.outputs.save-var == 'yes' }}
   #   run: echo "Run the test steps"
           
